chains:
  - name: cometbft
    enabled: true
    endpoint: grpc://localhost:9090
    ingress:
      type: collector
      decoder: proto
    egress:
      targets:
        - type: kafka
          topic: cometbft.consensus
        - type: file
          path: /tmp/cometbft-messages.log
    config:
      version: "0.38.0"
      timeout: 30s
      retry_count: 3

  - name: besu
    enabled: true
    endpoint: http://localhost:8545
    ingress:
      type: collector
      decoder: rlp
    egress:
      targets:
        - type: kafka
          topic: besu.consensus
    config:
      consensus_type: "ibft2"
      validator_count: 4
      timeout: 30s

  - name: kaia
    enabled: true
    endpoint: http://localhost:8551
    ingress:
      type: collector
      decoder: rlp
    egress:
      targets:
        - type: kafka
          topic: kaia.consensus
        - type: file
          path: /tmp/kaia-messages.log
    config:
      consensus_type: "istanbul"
      governance_id: "governance-1"
      timeout: 30s

router:
  rules:
    # Route CometBFT votes to Besu and Kafka
    - match:
        chain: cometbft
        message_type: vote
      forward:
        - chain: besu
        - sink: kafka://consensus.vote

    # Route Besu proposals to CometBFT
    - match:
        chain: besu
        message_type: proposal
      forward:
        - chain: cometbft
        - sink: kafka://consensus.proposal

    # Route all Kaia messages to monitoring
    - match:
        chain: kaia
      forward:
        - sink: kafka://monitoring.all
        - sink: file:///tmp/kaia-monitoring.log

    # Route high-priority messages to all chains
    - match:
        message_type: proposal
      forward:
        - chain: cometbft
        - chain: besu
        - chain: kaia
        - sink: kafka://consensus.proposals

# Global settings
global:
  log_level: info
  metrics_enabled: true
  health_check_interval: 30s
  max_message_size: 10MB
  buffer_size: 1000
